version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html/404.html
      - ./static:/usr/share/nginx/static
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
